# Generated by Django 5.0.6 on 2026-04-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gallery_1',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gallery_2',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='height',
            field=models.IntegerField(blank=True, help_text='Taille en cm', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='instagram',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.CharField(blank=True, help_text='Poste préféré', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='weight',
            field=models.IntegerField(blank=True, help_text='Poids en kg', null=True),
        ),
    ]
