# Generated by Django 5.0.6 on 2026-04-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(default=1)),
                ('match_number', models.IntegerField(default=1)),
                ('score_player1', models.IntegerField(blank=True, null=True)),
                ('score_player2', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programmé'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé'), ('WALKOVER', 'Forfait')], default='SCHEDULED', max_length=15)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('played_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['round_number', 'match_number'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sport', models.CharField(max_length=100)),
                ('format', models.CharField(choices=[('SINGLE_ELIMINATION', 'Élimination simple'), ('DOUBLE_ELIMINATION', 'Double élimination'), ('ROUND_ROBIN', 'Round Robin')], default='SINGLE_ELIMINATION', max_length=25)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('OPEN', 'Inscriptions ouvertes'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=15)),
                ('max_participants', models.IntegerField(default=8)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('prize', models.CharField(blank=True, max_length=200)),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.IntegerField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
